defaults:
  - _self_
  - model: rnn
  - optimizer: sgd
model:
  embedding_dim: 100
  hidden_dim: 50
seed: 1234
batch_size: 64
epochs: 100
lr: 0.01
device: cpu
name: null
group: null

wandb:
  entity: crutch
  project: "Deep Learning models for Sentence Classification"