defaults:
  - _self_
  - model: packed_rnn
  - optimizer: adam
  - regularizer: l2
  - base: rnn
model:
  embedding_dim: 100
  hidden_dim: 200
  dropout: ${dropout}

regularizer:
  alpha: 0.0006332825849228081
  use: false

batch_size: 32
lr: 0.0008726644867850513
patience: 10
grad_clip_threshold: 3.409241906075233
dropout: 0.014878368933965491

wandb:
  entity: crutch
  project: "Deep Learning models for Sentence Classification"

seed: 1234
epochs: 500
device: cpu
name: null
group: 2_gensim
