defaults:
  - _self_
  - model: packed_rnn
  - optimizer: adadelta
model:
  embedding_dim: 100
  hidden_dim: 200
  dropout: ${dropout}
seed: 1234
dropout: 0
batch_size: 32
epochs: 100
lr: 0.1
device: cpu
name: null
group: 1_c_regularization

wandb:
  entity: crutch
  project: "Deep Learning models for Sentence Classification"