_target_: model.rnn.Encoder
hidden_size: ${hidden_size}
bidirectional: false
base:
    _target_: torch.nn.LSTM
    input_size: ${hidden_size}
    hidden_size: ${hidden_size}
    bidirectional: ${encoder.bidirectional}

